'use client';
import { motion, AnimatePresence } from 'framer-motion';
import gsap from 'gsap';
import { ArrowUpRight,Award,BarChart3,CalendarDays,Check,ChevronRight,CircleDot,Compass,Dumbbell,Flame,Grip,Link2,MapPin,Menu,Plus,Search,Settings2,Sparkles,Swords,Target,Trophy,X } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';

const events=[
{name:'Paris Open No-Gi',date:'14 sept. 2026',city:'Paris',result:'🥇 Or',matches:'5–0',category:'Adult · -76 kg',score:9.2,accent:'gold',tag:'Soumission x3',note:'Très bonne gestion du rythme. À revoir : entrées sur garde assise.'},
{name:'ADCC French Open',date:'30 août 2026',city:'Lyon',result:'🥈 Argent',matches:'4–1',category:'Adult · -76 kg',score:8.4,accent:'violet',tag:'Points : 15–4',note:'Top pressure et transitions. Finale perdue sur pénalité.'},
{name:'Grappling Industries',date:'12 juil. 2026',city:'Bordeaux',result:'🥉 Bronze',matches:'3–1',category:'Gi · -76 kg',score:7.8,accent:'coral',tag:'4 combats',note:'Bonne défense de leg locks. Manque de précision au collar drag.'}];
function ScoreRing({value}:{value:number}){return <div className="score-ring" style={{'--score':`${value*10}%`} as React.CSSProperties}><span>{value}</span><small>/10</small></div>}
export default function Home(){
 const [panel,setPanel]=useState(false),[url,setUrl]=useState(''),[imported,setImported]=useState(false),[active,setActive]=useState('Vue d’ensemble'); const headline=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(headline.current)gsap.fromTo(headline.current,{y:16,opacity:0},{y:0,opacity:1,duration:.65,ease:'power3.out'})},[]);
 const add=()=>{if(url.trim()){setImported(true);setTimeout(()=>{setPanel(false);setImported(false);setUrl('')},1100)}};
 return <main className="min-h-screen bg-[#F6F7F5] text-[#15221E]">
 <aside className="sidebar"><div className="brand"><span className="brand-mark"><Grip size={21}/></span><span>rollbook</span></div><nav>{[[Compass,'Vue d’ensemble'],[Trophy,'Compétitions'],[BarChart3,'Statistiques'],[Dumbbell,'Journal d’entraînement']].map(([Icon,label])=><button key={String(label)} onClick={()=>setActive(String(label))} className={active===label?'nav-active':''}><Icon size={19}/><span>{String(label)}</span></button>)}</nav><div className="side-bottom"><button><Settings2 size={19}/><span>Préférences</span></button><div className="profile"><div>AL</div><span><b>Adel Loukal</b><small>Ceinture violette</small></span><ChevronRight size={16}/></div></div></aside>
 <section className="content"><header className="topbar"><button className="mobile-menu"><Menu size={22}/></button><div className="season"><CalendarDays size={17}/><span>Saison 2026</span><ChevronRight size={15}/></div><div className="top-actions"><button className="icon-btn"><Search size={19}/></button><button className="add-button" onClick={()=>setPanel(true)}><Plus size={18}/>Ajouter une compétition</button></div></header>
 <div className="page-inner"><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="eyebrow"><span/>TON CARNET DE COMPÉTITION</motion.div><h1 ref={headline}>Chaque passage sur le tapis<br/><em>devient une donnée.</em></h1><p className="intro">Une vision claire de ta saison, de tes progrès et de ce qui mérite ton attention.</p>
 <section className="stats-grid"><motion.article initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.15}} className="stat-card primary"><div><span className="stat-label">Bilan de saison</span><strong>12 <i>victoires</i><br/>3 <i>défaites</i></strong><div className="positive"><ArrowUpRight size={15}/> +18% vs saison précédente</div></div><div className="win-chart"><svg viewBox="0 0 110 82"><path d="M3 65 C15 52 17 55 27 43 S45 52 54 30 S70 38 81 17 S97 27 107 5" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg><span>80% de victoires</span></div></motion.article>
 <motion.article initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.22}} className="stat-card"><span className="stat-label">Combats disputés</span><div className="big-number">15</div><div className="mini-bars">{[34,70,48,85,62,93,78].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div><small>5 compétitions · 2026</small></motion.article>
 <motion.article initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.29}} className="stat-card"><span className="stat-label">Finition favorite</span><div className="finish"><span><Swords size={18}/></span><div><b>Rear naked choke</b><small>4 soumissions</small></div></div><div className="progress"><i style={{width:'72%'}}/></div><small>72% de tes finitions</small></motion.article></section>
 <section className="section-head"><div><span className="eyebrow"><span/>DERNIÈRES COMPÉTITIONS</span><h2>Les moments qui comptent</h2></div><button className="text-button">Voir tout <ChevronRight size={16}/></button></section>
 <section className="event-grid">{events.map((event,i)=><motion.article key={event.name} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.32+i*.08}} whileHover={{y:-5}} className="event-card"><div className={`event-visual ${event.accent}`}><div className="grain"/><span className="event-date">{event.date}</span><div className="event-monogram">{event.name.split(' ').slice(0,2).map(w=>w[0]).join('')}</div><span className="event-city"><MapPin size={14}/>{event.city}</span></div><div className="event-body"><div className="result-row"><span className="result">{event.result}</span><ScoreRing value={event.score}/></div><h3>{event.name}</h3><p>{event.category}</p><div className="event-data"><span><Swords size={15}/>{event.matches}</span><span><Target size={15}/>{event.tag}</span></div><div className="reflection"><Sparkles size={15}/><span>{event.note}</span></div></div></motion.article>)}</section>
 <section className="review-card"><div className="review-icon"><Flame size={23}/></div><div><span className="eyebrow"><span/>POINT D’ATTENTION</span><h3>Ton jeu de jambes a pris le dessus.</h3><p>Tu marques 63% de tes points en position dominante. Prochain axe : convertir tes passages de garde plus vite.</p></div><button className="round-arrow"><ArrowUpRight size={19}/></button></section></div></section>
 <nav className="mobile-nav">{[[Compass,'Accueil'],[Trophy,'Compétitions'],[Plus,'Ajouter'],[BarChart3,'Stats']].map(([Icon,label])=><button key={String(label)} onClick={()=>label==='Ajouter'&&setPanel(true)} className={label==='Accueil'?'selected':''}><Icon size={20}/><span>{String(label)}</span></button>)}</nav>
 <AnimatePresence>{panel&&<motion.div className="modal-wrap" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><button className="close" onClick={()=>setPanel(false)}><X size={19}/></button><div className="import-mark"><Link2 size={23}/></div><span className="eyebrow"><span/>IMPORTER UNE ÉPREUVE</span><h2>Ajoute une compétition<br/>depuis son lien.</h2><p>Colle une URL Smoothcomp, CFJJB ou d’un autre organisateur. Les infos publiques seront préremplies.</p><label>LIEN DE LA COMPÉTITION</label><input autoFocus placeholder="https://smoothcomp.com/event/..." value={url} onChange={e=>setUrl(e.target.value)}/><button className="import-button" onClick={add}>{imported?<><Check size={19}/>Compétition importée</>:<>Importer la compétition <ArrowUpRight size={18}/></>}</button><small><CircleDot size={13}/>Tu pourras compléter les résultats et ton analyse ensuite.</small></motion.div></motion.div>}</AnimatePresence></main>}
